modeloMeseros/Models/mesas.cs
using System.ComponentModel.DataAnnotations;

namespace modeloMeseros.Models
{
    public class mesas
    {
        [Key]

        public int id { get; set; }

        public int numero { get; set; }
        public int capacidad { get; set; }
        public string disponibilidad { get; set; }
        public int estado { get; set; }
    }
}

modeloMeseros/Controllers/MesasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using modeloMeseros.Models;

namespace modeloMeseros.Controllers
{
    public class MesasController : Controller
    {
        private readonly MeserosContext _context;

        public MesasController(MeserosContext context)
        {
            _context = context;
        }

        // GET: Mesas
        public async Task<IActionResult> Index()
        {
            return View(await _context.mesas.ToListAsync());
        }

        // GET: Mesas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mesas = await _context.mesas
                .FirstOrDefaultAsync(m => m.id == id);
            if (mesas == null)
            {
                return NotFound();
            }

            return View(mesas);
        }

        // GET: Mesas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Mesas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,numero,capacidad,disponibilidad,estado")] mesas mesas)
        {
            if (ModelState.IsValid)
            {
                _context.Add(mesas);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(mesas);
        }

        // GET: Mesas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mesas = await _context.mesas.FindAsync(id);
            if (mesas == null)
            {
                return NotFound();
            }
            return View(mesas);
        }

        // POST: Mesas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,numero,capacidad,disponibilidad,estado")] mesas mesas)
        {
            if (id != mesas.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(mesas);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!mesasExists(mesas.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(mesas);
        }

        // GET: Mesas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mesas = await _context.mesas
                .FirstOrDefaultAsync(m => m.id == id);
            if (mesas == null)
            {
                return NotFound();
            }

            return View(mesas);
        }

        // POST: Mesas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var mesas = await _context.mesas.FindAsync(id);
            if (mesas != null)
            {
                _context.mesas.Remove(mesas);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Ocupar(int id)
        {
            var mesa = await _context.mesas.FindAsync(id);
            if (mesa == null)
            {
                return NotFound();
            }

            mesa.estado = 1;  // 1 representa "ocupado"
            mesa.disponibilidad = "ocupado";

            try
            {
                _context.Update(mesa);
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!MesasExists(mesa.id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            HttpContext.Session.Clear();


            HttpContext.Session.SetInt32("id_mesa", id);

            return RedirectToAction("Create", "Pedido_Local");
        }


        // Método para verificar si la mesa existe
        private bool MesasExists(int id)
        {
            return _context.mesas.Any(e => e.id == id);
        }

        public async Task<IActionResult> MesasOcupadas()
        {
            var mesasOcupadas = await _context.mesas
                .Where(m => m.estado == 1)  // Filtrar mesas ocupadas
                .ToListAsync();

            return View(mesasOcupadas);
        }


        private bool mesasExists(int id)
        {
            return _context.mesas.Any(e => e.id == id);
        }

        public IActionResult BuscarPedido(int id)
        {

            HttpContext.Session.Clear();

            HttpContext.Session.SetInt32("id_mesaOcupada", id);


            return RedirectToAction("Create", "Pedido_Local");
        }


    }
}

modeloMeseros/Views/Mesas/Create.cshtml
@model modeloMeseros.Models.mesas

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>mesas</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="numero" class="control-label"></label>
                <input asp-for="numero" class="form-control" />
                <span asp-validation-for="numero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="capacidad" class="control-label"></label>
                <input asp-for="capacidad" class="form-control" />
                <span asp-validation-for="capacidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="disponibilidad" class="control-label"></label>
                <input asp-for="disponibilidad" class="form-control" />
                <span asp-validation-for="disponibilidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="estado" class="control-label"></label>
                <input asp-for="estado" class="form-control" />
                <span asp-validation-for="estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

modeloMeseros/Views/Mesas/Delete.cshtml
@model modeloMeseros.Models.mesas

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>mesas</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.numero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.numero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.capacidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.capacidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.disponibilidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.disponibilidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.estado)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

modeloMeseros/Views/Mesas/Details.cshtml
@model modeloMeseros.Models.mesas

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>mesas</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.numero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.numero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.capacidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.capacidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.disponibilidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.disponibilidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.estado)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

modeloMeseros/Views/Mesas/Edit.cshtml
@model modeloMeseros.Models.mesas

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>mesas</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="numero" class="control-label"></label>
                <input asp-for="numero" class="form-control" />
                <span asp-validation-for="numero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="capacidad" class="control-label"></label>
                <input asp-for="capacidad" class="form-control" />
                <span asp-validation-for="capacidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="disponibilidad" class="control-label"></label>
                <input asp-for="disponibilidad" class="form-control" />
                <span asp-validation-for="disponibilidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="estado" class="control-label"></label>
                <input asp-for="estado" class="form-control" />
                <span asp-validation-for="estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

modeloMeseros/Views/Mesas/Index.cshtml
@model IEnumerable<modeloMeseros.Models.mesas>

@{
    Layout = "~/Views/Shared/LayoutVertical.cshtml";
}

<head>
    <link rel="stylesheet" href="/css_C/Style.css" asp-append-version="true" />
</head>

<div class="container mt-4">
    <!-- Menú de navegación entre las vistas de mesas -->
    <ul class="nav nav-tabs" id="mesasTab" role="tablist">
        <li class="nav-item" role="presentation">
            <a class="nav-link active" id="mesasDisponibles-tab" data-bs-toggle="tab" href="#mesasDisponibles" role="tab">Mesas Disponibles</a>
        </li>
        <li class="nav-item" role="presentation">
            <a class="nav-link" id="mesasOcupadas-tab" data-bs-toggle="tab" href="#mesasOcupadas" role="tab">Mesas Ocupadas</a>
        </li>
    </ul>

    <div class="tab-content mt-3" id="mesasTabContent">
        <!-- Vistas de mesas disponibles -->
        <div class="tab-pane fade show active" id="mesasDisponibles" role="tabpanel">
            <h2 class="mb-3 text-center">Mesas Disponibles</h2>
            <div class="row">
                @foreach (var item in Model.Where(m => m.estado == 0))
                {
                        <div class="col-md-4 mb-3">
                            <div class="card shadow-sm">
                                <div class="card-body text-center">
                                    <h5 class="card-title">Mesa @item.numero</h5>
                                    <p class="card-text">Capacidad: @item.capacidad personas</p>
                                    <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#mesaModal-@item.id">Ocupar</button>
                                </div>
                            </div>
                        </div>
                }
            </div>
        </div>

        <!-- Vistas de mesas ocupadas -->
        <div class="tab-pane fade" id="mesasOcupadas" role="tabpanel">
            <h2 class="mb-3 text-center">Mesas Ocupadas</h2>
            <div class="row">
                @foreach (var item in Model.Where(m => m.estado == 1))
                {
                        <div class="col-md-4 mb-3">
                            <div class="card shadow-sm bg-warning">
                                <div class="card-body text-center">
                                    <h5 class="card-title">Mesa @item.numero</h5>
                                    <p class="card-text">Capacidad: @item.capacidad personas</p>
                                    <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#detallePedidoModal-@item.id">
                                        
                                            Ver detalle
                                    </button>
                                </div>
                            </div>
                        </div>
                }
            </div>
        </div>
    </div>
</div>

<!-- Modales para mesas disponibles -->
@foreach (var item in Model.Where(m => m.disponibilidad.ToLower() == "libre"))

{
    <!-- Modal corregido -->
    <div class="modal fade" id="mesaModal-@item.id" tabindex="-1" data-bs-backdrop="false" data-bs-keyboard="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Detalles de Mesa @item.numero</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                </div>
                <div class="modal-body">
                    <p><strong>Capacidad:</strong> @item.capacidad personas</p>
                    <p>¿Quieres ocupar esta mesa?</p>
                </div>
                <div class="modal-footer">
                    <form method="post" asp-controller="Mesas" asp-action="Ocupar" asp-route-id="@item.id">
                        @* <a class="btn btn-info text-dark" asp-area="" asp-controller="Pedido_Local" asp-action="Create">
                            Ocupar mesa
                        </a> *@
                        <button type="submit" class="btn btn-info text-dark">
                            Ocupar mesa

                        </button>
                    </form>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>

}

<!-- Modales para mesas ocupadas -->
@foreach (var item in Model.Where(m => m.disponibilidad.ToLower() == "ocupado"))

{
           <div class="modal fade" id="detallePedidoModal-@item.id" tabindex="-1" data-bs-backdrop="false" data-bs-keyboard="true">

            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Detalles del Pedido - Mesa @item.numero</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal"></button>
                    </div>
                    <div class="modal-body">
                        <p><strong>Capacidad:</strong> @item.capacidad personas</p>
                        <p><strong>Estado:</strong> Ocupada</p>
                    </div>
                    <div class="modal-footer">
                    <form method="post" asp-controller="Mesas" asp-action="BuscarPedido" asp-route-id="@item.id">
                        <button type="submit" class="btn btn-info text-dark">
                            Ver Detalle Orden

                        </button>
                    </form>
                    @*                         <button type="button" class="btn">
                            <a class="btn btn-info text-dark" asp-area="" asp-controller="Pedido_Local" asp-action="Create"> 
                                Ver Detalle Orden
                             </a>
                        </button> *@
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                    </div>
                </div>
            </div>
        </div>
}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>